### ISSUE TITLE
Broken: jellyfin-media-player-deb

### ISSUE THREAD

**Issue by Rockstar9604** [pacstall/pacstall-programs#6061] opened 2024-05-29 10:02 UTC
### Package name

jellyfin-media-player-deb

### Version

1.10.1

### Pacstall version

5.1.1

### Relevant log output

```shell
gianluca@gianluca-ThinkPadL15 ~> pacstall -I jellyfin-media-player-deb
(jellyfin-media-player-deb) Do you want to view/edit the pacscript? [y/N] n
[+] INFO: Sourcing pacscript
[!] ERROR: Package does not contain 'source'
[+] INFO: Cleaning up
```

**Comment by Rockstar9604** [comment] 2024-05-29 10:08
This is happening for fsearch-deb and virtualbox-deb too.

Maybe this is caused by #6047 but I'm not sure.

**Comment by oklopfer** [comment] 2024-05-30 00:13
> This is happening for fsearch-deb and virtualbox-deb too.
> 
> Maybe this is caused by #6047 but I'm not sure.

this would indeed be caused by #6047 - can you please describe what you are running on?

**Comment by Rockstar9604** [comment] 2024-05-30 10:09
> > This is happening for fsearch-deb and virtualbox-deb too.
> > Maybe this is caused by #6047 but I'm not sure.
> 
> this would indeed be caused by #6047 - can you please describe what you are running on?

`lsb_release -a` output:
```
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
```
`uname -a` output:
```
Linux gianluca-ThinkPadL15 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by oklopfer** [comment] 2024-05-30 19:17
@Rockstar9604 this will be fixed by the linked PR, to allow for easier `else` selection with DISTRO enhanced arrays. For now, it should be able to work if you exit the pacscripts, comment out all but 1 of the source options, and then remove the enhancements from that array, making it just “source” and “sha256sums”. Also, fsearch-deb’s links are dead, so that one probably won’t work anyways.

**Closed** 2024-05-31 12:07 UTC
Labels: Broken
