### ISSUE TITLE
PacReq: Darling

### ISSUE THREAD

**Issue by 0xMaluco** [pacstall/pacstall-programs#4484] opened 2023-08-31 06:24 UTC
### Types

-bin (Binary release of the package), -git (Compiled off of the latest commit of the package)

### URL

https://github.com/darlinghq/darling.git

### [Dependencies](https://docs.darlinghq.org/build-instructions.html#dependencies)
```bash 
sudo apt install cmake automake clang-15 bison flex libfuse-dev libudev-dev pkg-config libc6-dev-i386 \
gcc-multilib libcairo2-dev libgl1-mesa-dev curl libglu1-mesa-dev libtiff5-dev \
libfreetype6-dev git git-lfs libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev \
libbsd-dev libxrandr-dev libxcursor-dev libgif-dev libavutil-dev libpulse-dev \
libavformat-dev libavcodec-dev libswresample-dev libdbus-1-dev libxkbfile-dev \
libssl-dev libstdc++-12-dev
```
### [Fetch the Sources](https://docs.darlinghq.org/build-instructions.html#fetch-the-sources)
```bash 
git clone --recursive https://github.com/darlinghq/darling.git
```

### [Build](https://docs.darlinghq.org/build-instructions.html#build)

```bash 

# Move into the cloned sources
cd darling

# Remove prior install of Darling
tools/uninstall

# Make a build directory
mkdir build && cd build

# Configure the build
cmake ..

# Build and install Darling
make
sudo make install
```

### Additional context

https://www.darlinghq.org/

**Comment by spaceguybob** [comment] 2023-09-07 21:53
this is possible, maybe not easy though

**Comment by Gmaia325** [comment] 2023-09-08 04:17
Can you merge this with PacReq/Issue with [Issue-4178](https://github.com/pacstall/pacstall-programs/issues/4178)?

**Comment by Gmaia325** [comment] 2023-09-08 04:22
Also, I found that Darling has a .deb file on their Github: [Alpha Release: July 4, 2022 - Darwin/macOS Emulation Layer for Linux](https://github.com/darlinghq/darling/releases/tag/v0.1.20220704)

**Comment by Elsie19** [comment] 2024-12-08 04:09
Duplicate of #4178.

**Closed by Elsie19** 2024-12-08 04:09 UTC
Labels: package request
