### ISSUE TITLE
PacReq: Stremio

### ISSUE THREAD

**Issue by KierPrev** [pacstall/pacstall-programs#5471] opened 2024-01-20 20:21 UTC
### Types

nosuffix (Compiled off of the released source code)

### URL

https://github.com/Stremio/stremio-shell

### Additional context

I don't  know which version is better for pacstall. There's a deb file too, but it had the dependencies broken.

**Comment by Elsie19** [comment] 2024-01-21 14:59
Duplicate of #5212.

**Closed by Elsie19** 2024-01-21 14:59 UTC
Labels: package request
